### PR TITLE
The 'context' ext key is now a constant

### PR DESCRIPTION
**Pull request by mikemcgowan**
A [recent commit](https://github.com/xAPI-vle/moodle-logstore_xapi/commit/b2407942b36fffba2f1e2ec7b0325c0b9fc927de) requires the 'context' ext key and has gone to rather elaborate lengths to obtain it. It's had to instantiate `\MXTranslator\Events\Event` and then invoke its `read` method. This seems unwieldy.

Therefore, I've made the 'context' ext key a class constant than can be easily accessed outside of the class itself. It's no longer necessary to actually instantiate the class and invoke its `read` method to get it.

This seems a sensible thing to do. After sending a statement, one way wish to obtain the event itself (within the 'context' of the statement) and knowing the 'context' ext key is required.

Also see [this PR](https://github.com/xAPI-vle/moodle-logstore_xapi/pull/112).

### CODE REVIEW

**Comment by davidpesce** [comment]
@mikemcgowan thanks for contributing this. I'm in the midst of combining this repository (and expander/emitter) into the logstore. If you take a look a the logstore repo v2.0.0 branch, you'll see how I have things set up.

**Comment by mikemcgowan** [comment]
Oh, okay. I see. Andrew Downes mentioned about combining the repositories.

What are you planning on doing with the three underlying 'Learning Locker' repos and their corresponding Packagist packages, then? Hopefully they'll be kept (even if no longer maintained)?

```
        "learninglocker/moodle-log-expander": "1.5.0",
        "learninglocker/moodle-xapi-translator": "1.7.0",
        "learninglocker/xapi-recipe-emitter": "1.6.1",
```

The reason I ask because I've just written a [logstore plugin](https://github.com/mikemcgowan/moodle-elasticsearch/tree/master/plugins/admin/tool/log/store/elasticsearch) that sends xAPI statements to Elasticsearch (instead of an LRS) which I originally based on v1.4.0 of [moodle-logstore_xapi](https://github.com/xAPI-vle/moodle-logstore_xapi). Like the logstore xAPI plugin, it's built on top of the three underlying 'Learning Locker' repos.

Originally I didn't really want to create an entirely new logstore plugin; I had planned to use all four of these ones (and submit some PRs to refactor where necessary) but having had a closer look at the code, I judged it to be too much work. There are too many tightly coupled dependencies that would have taken too much time to unravel. For example, it's not possible to create an instance of `\XREmitter\Controller` without having an instance of `\XREmitter\Repository`, and it's not possible to create an instance of _that_ without having an instance of `\TinCan\RemoteLRS`.

It would be an improvement to replace some concrete classes with interfaces. For example, `\XREmitter\Controller` maintains a reference to a `\XREmitter\Repository`, but only ever invokes its `createEvents` method. Instead of the constructor of `\XREmitter\Controller` taking a concrete class, it could take an interface (say, `IRepository`) with a single method (of `createEvents`). Then, *any* concrete class implementing this interface could be injected into `\XREmitter\Controller`. (It could be a class that sends xAPI statements to an LRS, or it could be one that sends xAPI statements to Elasticsearch.)

It would also be an improvement to inject dependencies into classes rather than have classes create their own dependencies with `new`. For example, the `store` class's `process_events()` method does this:

```php
        // Initializes required services.
        $xapicontroller = new xapi_controller($this->connect_xapi_repository());
        $moodlecontroller = new moodle_controller($this->connect_moodle_repository());
        $translatorcontroller = new translator_controller();
```

It's not possible, then, to have automated tests that test the `process_events()` method in isolation (and indeed the test coverage of the plugin doesn't cover this, or anything else in the `classes/` directory). Instead of using `new`, dependencies could be injected into the class or method either as additional constructor or method parameters, or with a dependency injection container like [Pimple](https://pimple.sensiolabs.org/). (The latter is the approach I've taken for my Elasticsearch logstore plugin.)

When the dust settles on your major v2 refactor of combining these four plugins, I can take another look and maybe try to implement some of the above suggestions, and get maybe get some test coverage of the classes in the `classes/` directory going - the `store` class in particular.

**Comment by davidpesce** [comment]
@mikemcgowan, that would be awesome! There's one bug with v2.0.0 (I've identified it). Just working on resolving it and I'll be pushing it live. I'm hopeful I can resolve it today. 

In terms of what is happening to the downstream (individual) repositories, they will be deprecated. 

P.S. Nice work on the elasticsearch plugin. It's been on my todo list for a while!

**Comment by davidpesce** [comment]
@mikemcgowan v2.0.0 is available

**Comment by ryansmith94** [comment]
Thread to discuss architectural changes https://github.com/xAPI-vle/moodle-logstore_xapi/issues/115

**Comment by mikemcgowan** [comment]
Closing this PR as it's now redundant as of v2.0.0 of the main plugin.

[See this PR instead](https://github.com/xAPI-vle/moodle-logstore_xapi/pull/112)

**Pull request closed without merging**
