### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by davidpesce**
Incorporated https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/43 along with merge conflicts.

### CODE REVIEW

**Comment by davidpesce** [comment]
@garemoko This is your PR with the merge conflicts resolved. All tests pass, but when using the actual plugin, I am not seeing the results of answering each question.

Statement order goes:
1. Viewed quizname
2. Started attempt#
3. Viewed quizname (duplicate)
4. Viewed quizname (duplicate)

Are you using this in production? Any ideas as to why it's sending the viewed statement twice at the end and not each answer?

**Comment by garemoko** [comment]
@davidpesce it's been so long since I looked at this I couldn't tell you. I don't believe we have anybody using this in production. Maybe the wrong recipe is being used so you are getting viewed statements instead of the answered statements? Do you have a 2 question quiz?

**Comment by davidpesce** [comment]
@garemoko oddly, yes, I do have a two question quiz. Is that the issue?

**Comment by garemoko** [comment]
@davidpesce without looking at the code, the fact that you have 2 extra statements and 2 missing statements seems like too much of a coincidence not to be related.

**Comment by davidpesce** [comment]
@ryansmith94 I have this working now. Which function names are too long?

**Pull request merged**
