### PR TITLE
abandoned extends completed

### PR DESCRIPTION
**Pull request by garemoko**
Aims to address https://github.com/jlowe64/moodle-logstore_xapi/issues/40

Really the abandoned event needs more love. This PR is just about maintaining the status quo.

### CODE REVIEW

**Comment by garemoko** [comment]
I'll probably re-do this after #26 merges due to likely conflicts. Leaving this open until then in case anybody wants to comment on the approach.

**Comment by jlowe64** [comment]
I'm gonna go over the code for https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/26/ and see if I see any glaring issues. I'd like it to be merged so that we can do a proper release on the main plugin.

**Comment by garemoko** [comment]
Now rolled into #26

**Comment by ryansmith94** [comment]
Fair enough, thanks for closing.

**Pull request closed without merging**
