### PR TITLE
add score and success properties; amend duration

### PR DESCRIPTION
**Pull request by garemoko**
Replaces attempt_result with a collection of score properties.

Adds attempt_success. This is null if it is not possible to calculate success (e.g. if there is no pass grade). 

Amends the duration format. It's very unlikely that quiz attempt duration would run into days and I suspect even hours are rare. Due to problems converting seconds to other time periods, it's better to record seconds where times are measured in seconds and let reporting systems handle that as they see fit. See [ISO 8601 durations](https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#46-iso-8601-durations)

Docs and test changes still to do.

### CODE REVIEW

**Comment by ryansmith94** [comment]
Can you push another commit in to trigger Travis. Not sure why it didn't run on that last commit.

**Comment by garemoko** [comment]
@ryansmith94 any thoughts on how you'd like to handle this? Either copy the function, make it public or something else?

**Comment by ryansmith94** [comment]
Since `AttemptReviewedTest extends AttemptStartedTest`, `constructAttempt` should be made `protected` in `AttemptStartedTest` to call it from `AttemptReviewedTest`. However, due to this inheritance and the use of [`array_merge`](https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/23/files#diff-1982cff73bb9fb2a172626642349eb61R16) you should be able to remove [line 17](https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/23/files#diff-1982cff73bb9fb2a172626642349eb61R17) because `attempt` is [already added to the array by `AttemptStartedTest`](https://github.com/LearningLocker/Moodle-xAPI-Translator/blob/master/tests/AttemptStartedTest.php#L17)

**Comment by garemoko** [comment]
Of course! Why didn't i think of that?

**Comment by ryansmith94** [comment]
:smile_cat:

**Comment by garemoko** [comment]
@ryansmith94 ready for review

**Pull request merged**
