### PR TITLE
Quiz more types

### PR DESCRIPTION
**Pull request by garemoko**
Related to https://github.com/LearningLocker/Moodle-Log-Expander/pull/35. No changes to the emitter are required since I built the question statement emitter with these kinds of additions in mind. 

Needs docs and tests.

### CODE REVIEW

**Comment by garemoko** [comment]
Now also handles calculated question types (untested).

**Comment by garemoko** [comment]
Regarding docs, see https://github.com/LearningLocker/Moodle-Log-Expander/pull/35#issuecomment-230805692

I still need to do tests here though.

**Comment by garemoko** [comment]
@ryansmith94 @jlowe64 I'd appreciate a second pair of eyes on why this is falling with "Undefined offset: 1" on line 233 of QuestionSubmittedTest.php. 

From my reading of the code, `$input['attempt']->questions` should be set as an array with an index up to 10 by line 19 in `constructInput`.

Any ideas?

**Comment by garemoko** [comment]
@jlowe64 @ryansmith94 - figured it out. For some reason I need to regenerate the input for each event when there are multiple events of a given type.

**Comment by garemoko** [comment]
I'm not sure if the latest error is a code bug or a test bug. I'll have to poke it some more next week.

**Comment by garemoko** [comment]
@ryansmith94 @jlowe64 this is finally passing! As you can see the tests are hugely more robust, even for question types that were already covered. 

This PR doesn't include documentation changes as the theory is that we'll be able to automatically generate the docs once the test repo improvements land and after this is merged.

**Comment by ryansmith94** [comment]
Should get some time to review this soon

**Comment by garemoko** [comment]
@ryansmith94 @jlowe64 any chance of getting this reviewed and merged?

**Comment by jlowe64** [comment]
I won't be able to look at it before Christmas. Hopefully early new year?

**Comment by ryansmith94** [comment]
Also super busy at the moment, I'll hopefully get to look into merging stuff and sorting some things out here soon.

**Pull request merged**
